version: '3.7'
services:

  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${TYPE}_${PROJECT_NAME}_web_api
    container_name: ${TYPE}_${PROJECT_NAME}_web_api
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${FULL_PATH_DOMAIN_NAME}"
      traefik.backend: "${TYPE}-${PROJECT_NAME}-web-api"
      traefik.port: "${APPLICATION_PORT}"
    depends_on:
      - sys_postgres
    environment:
      TYPE: ${TYPE}
      PROJECT_NAME: ${PROJECT_NAME}
      VERSION: ${VERSION}
      FULL_PATH_DOMAIN_NAME: ${FULL_PATH_DOMAIN_NAME}
      DOMAIN_NAME: ${DOMAIN_NAME}
      APPLICATION_HOST: ${APPLICATION_HOST}
      APPLICATION_PORT: ${APPLICATION_PORT}
      POSTGRES_HOST: sys_postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCHEDULE_JOB_ENABLE: ${SCHEDULE_JOB_ENABLE}
    restart: always
    networks:
      - traefik


  sys_postgres:
    image: "postgres:latest"
    container_name: ${TYPE}_${PROJECT_NAME}_sys_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - sys_postgres_db:/var/lib/postgresql/data
    networks:
      - traefik

volumes:
  sys_postgres_db:
    name: ${TYPE}_${PROJECT_NAME}_sys_postgres_db

networks:
  traefik:
    external:
      name: traefik
