debug = true

logLevel = "INFO"
defaultEntryPoints = ["http"]



################################################################
# Docker Provider
################################################################

# Enable Docker Provider.
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "unix:///var/run/docker.sock"

# Enable watch docker changes.
#
# Optional
#
watch = true


################################################################
# 入口點設定
################################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"

[retry]

# 控制檯埠
[entryPoints.traefik-api]
address = ":4399"
# 如果不想公開控制檯，可以參考下面的配置生成你自己的 BA 賬號密碼
#[entryPoints.traefik-api.auth]
#[entryPoints.traefik-api.auth.basic]
#htpasswd -nb soulteary soulteary
users = ["soulteary:$apr1$hVv8KPU8$IiTLEE5QYKgd4mZuCXpOD."]
[entryPoints.traefik-api.redirect]
entryPoint = "https"
