debug = true

logLevel = "INFO"
defaultEntryPoints = ["http"]

[retry]

################################################################
# 入口點設定
################################################################

# 預設前端
[entryPoints]
  [entryPoints.http]
  address = ":80"

################################################################
# Docker Provider
################################################################

# Enable Docker Provider.
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "unix:///var/run/docker.sock"

# Enable watch docker changes.
#
# Optional
#
watch = true