debug = true

logLevel = "INFO"
defaultEntryPoints = ["http"]

[retry]

################################################################
# 入口點設定
################################################################

[entryPoints]
# 預設前端
  [entryPoints.http]
  address = ":80"

# traefik
  [entryPoints.traefik]
    address = ":9987"
    compress = true

    [entryPoints.traefik.auth.basic]
        users = ["admin:$apr1$kPpB.YwX$aCjyPTc6zoU3N32E48QeU/"]

[api]
  entryPoint = "traefik"
  dashboard = true
################################################################
# Docker Provider
################################################################

# Enable Docker Provider.
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "unix:///var/run/docker.sock"

# Enable watch docker changes.
#
# Optional
#
watch = true