// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-06-30 22:08:37.9419133 +0800 CST m=+0.803281901

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/cat": {
            "get": {
                "description": "get cat list with status from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓列表的lower",
                        "name": "lower",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓列表的upper",
                        "name": "upper",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓列表的狀態(待放養 : 0/預約中 : 1/繁殖中 : 2/收養中 : 3)",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.GetCatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new cat",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "貓的名稱",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的級別",
                        "name": "level",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的價格",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的pet幣",
                        "name": "pet_coin",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的預約價格",
                        "name": "reservation_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的即搶價格",
                        "name": "adoption_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的合約時間",
                        "name": "contract_days",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的合約增益",
                        "name": "contract_benefit",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cat/{catId}": {
            "put": {
                "description": "modify cat information to the database",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "貓的名稱",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的級別",
                        "name": "level",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的價格",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的pet幣",
                        "name": "pet_coin",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的預約價格",
                        "name": "reservation_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的即搶價格",
                        "name": "adoption_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的合約時間",
                        "name": "contract_days",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的合約增益",
                        "name": "contract_benefit",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的狀態(待放養 : 0/預約中 : 1/繁殖中 : 2/收養中 : 3)",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cat/{catId}/thumbnail": {
            "get": {
                "description": "get cat thumbnail from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/jpeg"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓的ID",
                        "name": "catId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "insert or update cat thumbnail to the database",
                "consumes": [
                    "image/jpeg"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓的ID",
                        "name": "catId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "File",
                        "description": "貓的縮圖檔案",
                        "name": "thumbnail",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/time/period": {
            "post": {
                "description": "Add a new timePeriod",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "起始時間(yyyy-MM-dd'T'HH:mm:ss)",
                        "name": "start_at",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "結束時間(yyyy-MM-dd'T'HH:mm:ss)",
                        "name": "end_at",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.CatItem": {
            "type": "object",
            "properties": {
                "adoption_price": {
                    "type": "integer"
                },
                "cat_thumbnail_path": {
                    "type": "string"
                },
                "contract_benefit": {
                    "type": "integer"
                },
                "contract_days": {
                    "type": "integer"
                },
                "level": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pet_coin": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "reservation_price": {
                    "type": "integer"
                }
            }
        },
        "controller.GetCatResponse": {
            "type": "object",
            "properties": {
                "cats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.CatItem"
                    }
                },
                "lower": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "upper": {
                    "type": "integer"
                }
            }
        },
        "controller.Message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "message"
                }
            }
        },
        "httputil.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
