// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-07-15 09:51:17.4033962 +0800 CST m=+10.304908601

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/login": {
            "post": {
                "description": "admin account login",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "管理員帳號",
                        "name": "account",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "管理員密碼",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/adoption/cats": {
            "get": {
                "description": "get adoption cat list with status from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓列表的lower",
                        "name": "lower",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓列表的upper",
                        "name": "upper",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓列表的領養狀態( 增值中: 1 / 已完成 :2 / 已售出 : 3 / 等待裂變 : 4)",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.GetCatListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/banner": {
            "post": {
                "description": "insert banner to the database",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "file",
                        "description": "banner的縮圖檔案",
                        "name": "banner",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "banner的排序",
                        "name": "order",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/banner/{bannerId}": {
            "get": {
                "description": "get banner thumbnail from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/jpeg"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "banner的ID",
                        "name": "bannerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "description": "modify banner information to the database",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "banner的ID",
                        "name": "bannerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "banner的縮圖檔案",
                        "name": "banner",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "banner的排序",
                        "name": "order",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/banners": {
            "get": {
                "description": "get banner list from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "banner列表的lower",
                        "name": "lower",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "banner列表的upper",
                        "name": "upper",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.GetBannerListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cat": {
            "post": {
                "description": "Add a new cat",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "貓的名稱",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的級別",
                        "name": "level",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的價格",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的押金",
                        "name": "deposit",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的pet幣",
                        "name": "pet_coin",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的預約價格",
                        "name": "reservation_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的即搶價格",
                        "name": "adoption_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的合約時間",
                        "name": "contract_days",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的合約增益",
                        "name": "contract_benefit",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cat/adoption/owner": {
            "put": {
                "description": "modify adoption cat owner",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓的ID識別",
                        "name": "cat_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "時段的ID識別",
                        "name": "time_schedule_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用戶的ID識別",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cat/reservation": {
            "post": {
                "description": "Add a new cat_user_reservation",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓的ID識別",
                        "name": "cat_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "時段的ID識別",
                        "name": "time_schedule_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cat/thumbnail": {
            "post": {
                "description": "insert or update cat thumbnail to the database",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "file",
                        "description": "貓的縮圖檔案",
                        "name": "thumbnail",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cat/thumbnail/{thumbnailId}": {
            "get": {
                "description": "get cat thumbnail from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/jpeg"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓的縮圖ID",
                        "name": "thumbnailId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cat/thumbnails": {
            "get": {
                "description": "get cat thumbnail list from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓縮圖列表的lower",
                        "name": "lower",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓縮圖列表的upper",
                        "name": "upper",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.GetCatThumbnailListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cat/thumbnails/{thumbnailId}/cats/{catId}": {
            "post": {
                "description": "link cat thumbnail with cat to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓的ID",
                        "name": "catId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓的縮圖ID",
                        "name": "thumbnailId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cats": {
            "get": {
                "description": "get cat list with status from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓列表的lower",
                        "name": "lower",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓列表的upper",
                        "name": "upper",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓列表的狀態(系統掛售中 : 1 / 期約到期掛售中 : 2/轉讓中 : 3 /領養增值中 :4 / 等待裂變中 :5)",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.GetCatListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cats/time/schedules/{scheduleId}": {
            "get": {
                "description": "get cat list with timeSchedule from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "時段的ID",
                        "name": "scheduleId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓列表的lower",
                        "name": "lower",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓列表的upper",
                        "name": "upper",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.GetTimeScheduleCatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/cats/{catId}": {
            "put": {
                "description": "modify cat information to the database",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓的ID",
                        "name": "catId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的名稱",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的級別",
                        "name": "level",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的價格",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的押金",
                        "name": "deposit",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的pet幣",
                        "name": "pet_coin",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的預約價格",
                        "name": "reservation_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的即搶價格",
                        "name": "adoption_price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的合約時間",
                        "name": "contract_days",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的合約增益",
                        "name": "contract_benefit",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "貓的狀態(系統掛售中 : 1 / 期約到期掛售中 : 2/轉讓中 : 3 /領養增值中 :4 / 等待裂變中 :5)",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/certificate/transfer/{transferId}": {
            "get": {
                "description": "get transfer cat certificate thumbnail from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/jpeg"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "transfer的ID",
                        "name": "transferId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/time/schedule": {
            "post": {
                "description": "Add a new timePeriod",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "起始時間(yyyy-MM-dd'T'HH:mm:ss)",
                        "name": "start_at",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "結束時間(yyyy-MM-dd'T'HH:mm:ss)",
                        "name": "end_at",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/time/schedules": {
            "get": {
                "description": "get timePeriod list with date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "時段列表的lower",
                        "name": "lower",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "時段列表的upper",
                        "name": "upper",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "時段列表的日期(yyyy-MM-dd)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.GetTimePeriodResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/time/schedules/{scheduleId}/cat/{catId}": {
            "post": {
                "description": "Add a new timePeriodCatPivot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓的ID",
                        "name": "catId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "時段的ID",
                        "name": "scheduleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/transfer/cats": {
            "get": {
                "description": "get transfer cat list with status from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貓列表的lower",
                        "name": "lower",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓列表的upper",
                        "name": "upper",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "貓列表的交易狀態( 待交易: 1 / 買家已上傳憑證 : 2/已完成 :3 /已取消)",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.GetCatListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/transfer/{transferId}/certificate": {
            "post": {
                "description": "post transfer cat certificate to database",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "transfer的ID",
                        "name": "transferId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "certificate的縮圖檔案",
                        "name": "certificate",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/transfer/{transferId}/migrate": {
            "post": {
                "description": "post transfer cat migrate to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "transfer的ID",
                        "name": "transferId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/user/info": {
            "get": {
                "description": "get user info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.GetUserInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "description": "user account login",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用戶手機號碼",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用戶密碼",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/user/logout": {
            "post": {
                "description": "user account logout",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/user/register": {
            "post": {
                "description": "user account register",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用戶手機號碼",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用戶手機認證碼",
                        "name": "valid_value",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用戶名稱",
                        "name": "user_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用戶密碼",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用戶二級密碼",
                        "name": "security_password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "推薦用戶識別碼",
                        "name": "identified_code",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "get user list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用戶列表的lower",
                        "name": "lower",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用戶列表的upper",
                        "name": "upper",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/controller.GetUserListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.BannerItem": {
            "type": "object",
            "properties": {
                "cat_thumbnail_path": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "order": {
                    "type": "integer"
                }
            }
        },
        "controller.CatItem": {
            "type": "object",
            "properties": {
                "adoption_price": {
                    "type": "integer"
                },
                "cat_thumbnail_path": {
                    "type": "string"
                },
                "contract_benefit": {
                    "type": "integer"
                },
                "contract_days": {
                    "type": "integer"
                },
                "deposit": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pet_coin": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "reservation_price": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "controller.CatThumbnailItem": {
            "type": "object",
            "properties": {
                "cat_thumbnail_path": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "controller.GetBannerListResponse": {
            "type": "object",
            "properties": {
                "banners": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.BannerItem"
                    }
                },
                "lower": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "upper": {
                    "type": "integer"
                }
            }
        },
        "controller.GetCatListResponse": {
            "type": "object",
            "properties": {
                "cats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.CatItem"
                    }
                },
                "lower": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "upper": {
                    "type": "integer"
                }
            }
        },
        "controller.GetCatThumbnailListResponse": {
            "type": "object",
            "properties": {
                "cat_thumbnails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.CatThumbnailItem"
                    }
                },
                "lower": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "upper": {
                    "type": "integer"
                }
            }
        },
        "controller.GetTimePeriodResponse": {
            "type": "object",
            "properties": {
                "lower": {
                    "type": "integer"
                },
                "time_periods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.TimePeriodItem"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "upper": {
                    "type": "integer"
                }
            }
        },
        "controller.GetTimeScheduleCatResponse": {
            "type": "object",
            "properties": {
                "cats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.CatItem"
                    }
                },
                "lower": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "upper": {
                    "type": "integer"
                }
            }
        },
        "controller.GetUserInfoResponse": {
            "type": "object",
            "properties": {
                "identified_code": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "controller.GetUserListResponse": {
            "type": "object",
            "properties": {
                "lower": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "upper": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.UserItem"
                    }
                }
            }
        },
        "controller.Message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "message"
                }
            }
        },
        "controller.TimePeriodItem": {
            "type": "object",
            "properties": {
                "cats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.CatItem"
                    }
                },
                "end_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "start_at": {
                    "type": "string"
                }
            }
        },
        "controller.UserItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "identified_code": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "httputil.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
